    %root E

    %tokens
    plus "\+"
    mult "\*"
    lparen "\("
    rparen "\)"
    num "[0-9]+"
    name "\w+"

    %grammar
    E := T Ep           # Exp op rhs ;
    Ep := plus T Ep      # Plus _ op rest
        | $ ;
    T := F Tp           # Term op rhs;
    Tp := mult F Tp      # Mult _ op rest
        | $ ;
    F := lparen E rparen      # Paren _ exp _
       | num           # Num val;
